### ISSUE TITLE
缺乏文件OSError: Can't load tokenizer for './models/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './models/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer. 请按任意键继续. . .

### ISSUE THREAD

**Issue by tcflying** [7eu7d7/APT-stable-diffusion-auto-prompt#2]
venv "E:\sd-APT-stable-diffusion-auto-prompt-master\venv\Scripts\Python.exe"
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Launching Web UI with arguments:
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\launch.py", line 152, in <module>
    start_webui()
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\launch.py", line 148, in start_webui
    import webui
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\webui.py", line 79, in <module>
    shared.sd_model = modules.sd_models.load_model()
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\modules\sd_models.py", line 154, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\repositories\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\repositories\stable-diffusion\ldm\models\diffusion\ddpm.py", line 461, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\repositories\stable-diffusion\ldm\models\diffusion\ddpm.py", line 519, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\repositories\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\repositories\stable-diffusion\ldm\modules\encoders\modules.py", line 141, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version, local_files_only=True)
  File "E:\sd-APT-stable-diffusion-auto-prompt-master\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1768, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for './models/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './models/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.
请按任意键继续. . .

**Comment by zakinp** [comment]
i meet the same problem. how to fix it?

**Comment by skyxiaowu** [comment]
同，求解

**Comment by Arcsion** [comment]
The author proposed solution [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2945#issuecomment-1285574017).

You have to [download CLIP manually from huggingface](https://huggingface.co/openai/clip-vit-large-patch14) and put everything into `/models/clip-vit-large-patch14`.
