### ISSUE TITLE
error: "cannot add middleware"

### ISSUE THREAD

**Issue by laurentopia** [7eu7d7/APT-stable-diffusion-auto-prompt#29]
after installing it.

```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "Z:\__TESTS\DreamArtist-stable-diffusion\launch.py", line 252, in <module>
    start()
  File "Z:\__TESTS\DreamArtist-stable-diffusion\launch.py", line 247, in start
    webui.webui()
  File "Z:\__TESTS\DreamArtist-stable-diffusion\webui.py", line 173, in webui
    app.add_middleware(GZipMiddleware, minimum_size=1000)
  File "Z:\__TESTS\DreamArtist-stable-diffusion\venv\lib\site-packages\starlette\applications.py", line 139, in add_middleware
    raise RuntimeError("Cannot add middleware after an application has started")
RuntimeError: Cannot add middleware after an application has started
Press any key to continue . . .
```

**Comment by emotionaldreams** [comment]
almost a year later, question still ignored. i too am having this issue. will move to a another program since it seems this is being ignored
