### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [7eu7d7/APT-stable-diffusion-auto-prompt#30]
Training at rate of 0.003 until step 8000
Preparing dataset...
100%|████████████████████████████████████████████████████████████████████████████████| 160/160 [00:01<00:00, 80.21it/s]
[Epoch 1: 0/1]loss: 0.0001802, grad:0.0000073, grad_neg:0.0000021:   0%|                      | 0/7999 [00:00<?, ?it/s]
Applying attention optimization: Doggettx... done.
*** Error completing request
*** Arguments: ('task(t6txrwmjoy64bsg)', 'style2', 114514, '0.003', 1, 'C:\\Users\\tomwe\\Desktop\\iconex', 'dream_artist', 512, 512, 8000, 2, 500, 'C:\\Users\\tomwe\\sd\\_textual_inversion_templates\\style_filewords.txt', False, False, 'masterpiece,best quality,style2', 'style2-neg,bad anatomy,bad hands,text,error,missing fingers,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,username,blurry,blurred', 20, 0, 7, -1.0, 512, 512, '5.0', '', True, True, False, 1, 1, 0.97, 25.0, 1.0, 25.0, 0.9, 0.999, False, 1, False, '0.000005') {}
    Traceback (most recent call last):
      File "C:\Users\tomwe\sd\modules\call_queue.py", line 58, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\tomwe\sd\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "C:\Users\tomwe\sd\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\ui.py", line 32, in train_embedding
        embedding, filename = dream_artist.cptuning.train_embedding(*args)
      File "C:\Users\tomwe\sd\extensions\DreamArtist-sd-webui-extension\scripts\dream_artist\cptuning.py", line 646, in train_embedding
        processed = processing.process_images(p)
      File "C:\Users\tomwe\sd\extensions\sd-webui-prompt-history\lib_history\image_process_hijacker.py", line 21, in process_images
        res = original_function(p)
      File "C:\Users\tomwe\sd\modules\processing.py", line 677, in process_images
        res = process_images_inner(p)
      File "C:\Users\tomwe\sd\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\Users\tomwe\sd\modules\processing.py", line 794, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\Users\tomwe\sd\modules\processing.py", line 1046, in sample
        self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
      File "C:\Users\tomwe\sd\extensions\sd-webui-neutral-prompt\lib_neutral_prompt\cfg_denoiser_hijack.py", line 254, in create_sampler_hijack
        if name.startswith(('DDIM', 'PLMS', 'UniPC')):
    AttributeError: 'NoneType' object has no attribute 'startswith'

---

**Comment by NoteToSelfFindGoodNickname** [comment]
It happens when you choose "Save an image to log directory each N steps, 0 to disable:
2

If you use something higher like 99, it works.

**Comment by NoteToSelfFindGoodNickname** [comment]
Happens if "Save an image to log..." <> 0.
